# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from robocasa.grpc import policy_service_pb2 as policy__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in policy_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyServiceStub(object):
    """PolicyService defines the gRPC interface between the environment (client)
    and the policy (server). This decouples simulation from inference so they
    can run in separate containers / processes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reset = channel.unary_unary(
                '/policy_service.PolicyService/Reset',
                request_serializer=policy__service__pb2.ResetRequest.SerializeToString,
                response_deserializer=policy__service__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.GetAction = channel.unary_unary(
                '/policy_service.PolicyService/GetAction',
                request_serializer=policy__service__pb2.ObservationRequest.SerializeToString,
                response_deserializer=policy__service__pb2.ActionResponse.FromString,
                _registered_method=True)


class PolicyServiceServicer(object):
    """PolicyService defines the gRPC interface between the environment (client)
    and the policy (server). This decouples simulation from inference so they
    can run in separate containers / processes.
    """

    def Reset(self, request, context):
        """Reset is called at the start of each episode so the server can prepare
        for a new rollout (e.g. store the action spec for random sampling).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAction(self, request, context):
        """GetAction is called every timestep. The client sends the current
        observation and the server returns the action to execute.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=policy__service__pb2.ResetRequest.FromString,
                    response_serializer=policy__service__pb2.ResetResponse.SerializeToString,
            ),
            'GetAction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAction,
                    request_deserializer=policy__service__pb2.ObservationRequest.FromString,
                    response_serializer=policy__service__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'policy_service.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('policy_service.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """PolicyService defines the gRPC interface between the environment (client)
    and the policy (server). This decouples simulation from inference so they
    can run in separate containers / processes.
    """

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_service.PolicyService/Reset',
            policy__service__pb2.ResetRequest.SerializeToString,
            policy__service__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_service.PolicyService/GetAction',
            policy__service__pb2.ObservationRequest.SerializeToString,
            policy__service__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
