# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: policy_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'policy_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14policy_service.proto\x12\x0epolicy_service\"x\n\x0cResetRequest\x12\x11\n\ttask_name\x18\x01 \x01(\t\x12\x18\n\x10task_description\x18\x02 \x01(\t\x12\x12\n\naction_dim\x18\x03 \x01(\x05\x12\x12\n\naction_low\x18\x04 \x03(\x02\x12\x13\n\x0b\x61\x63tion_high\x18\x05 \x03(\x02\" \n\rResetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xaf\x01\n\x12ObservationRequest\x12\x15\n\rprimary_image\x18\x01 \x01(\x0c\x12\x17\n\x0fsecondary_image\x18\x02 \x01(\x0c\x12\x13\n\x0bwrist_image\x18\x03 \x01(\x0c\x12\x0f\n\x07proprio\x18\x04 \x03(\x02\x12\x18\n\x10task_description\x18\x05 \x01(\t\x12\x14\n\x0cimage_height\x18\x06 \x01(\x05\x12\x13\n\x0bimage_width\x18\x07 \x01(\x05\" \n\x0e\x41\x63tionResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x02\x32\xa6\x01\n\rPolicyService\x12\x44\n\x05Reset\x12\x1c.policy_service.ResetRequest\x1a\x1d.policy_service.ResetResponse\x12O\n\tGetAction\x12\".policy_service.ObservationRequest\x1a\x1e.policy_service.ActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'policy_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESETREQUEST']._serialized_start=40
  _globals['_RESETREQUEST']._serialized_end=160
  _globals['_RESETRESPONSE']._serialized_start=162
  _globals['_RESETRESPONSE']._serialized_end=194
  _globals['_OBSERVATIONREQUEST']._serialized_start=197
  _globals['_OBSERVATIONREQUEST']._serialized_end=372
  _globals['_ACTIONRESPONSE']._serialized_start=374
  _globals['_ACTIONRESPONSE']._serialized_end=406
  _globals['_POLICYSERVICE']._serialized_start=409
  _globals['_POLICYSERVICE']._serialized_end=575
# @@protoc_insertion_point(module_scope)
